### PR TITLE
Use jq 🚀 to process JSON in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
@PrinsFrank I'm really sorry to pour out that letter soup :)
It made my brain hurt (a bit).

### CODE REVIEW

**Comment by szepeviktor** [comment]
BTW `"composer": "~2.3.0"` may replace this package ...
😢 
https://github.com/composer/composer/blob/main/doc/articles/composer-platform-dependencies.md#different-types-of-platform-packages

**Comment by PrinsFrank** [comment]
Hi @szepeviktor, thanks for your contribution, and I think you might be right that this package no longer has a use case. I will check if all functionality is provided, and then write a migration guide.

Currently, the checks are failing but that is because master is also failing. I will fix that later today, I might have not properly maintained this package so far. I will keep you updated! And thanks for introducing me to JQ!

**Comment by PrinsFrank** [comment]
@szepeviktor It looks like this package is indeed fully replaced by native composer functionality, so I will go ahead and mark this package as deprecated. Before that, I want to include your contribution though. Can you please update your branch with master?

There is a weird issue going on with a random package being included, I am still looking into that, but the rest of the issues related to the pipeline running in a too recent php version are now resolved. Maybe you have an idea how to solve the remaining issue as well?

**Comment by szepeviktor** [comment]
> Can you please update your branch with master?

Done 🍏

**Pull request merged**
