### PR TITLE
Do not run CI on Composer v1

### PR DESCRIPTION
**Pull request by szepeviktor**
@PrinsFrank I think Packagist.org is not full Composer v1 compatible.

### CODE REVIEW

**Comment by szepeviktor** [comment]
A quick Google search reveals that some Composer versions are broken.
https://stackoverflow.com/a/63801390

**Comment by PrinsFrank** [comment]
@szepeviktor Thanks for looking into the issues. As this package is now abandoned anyway, I wouldn't spend any more time on this. Thanks for your support and your alertness regarding this being a feature in composer itself now. Makes less code to maintain! I marked the package as abandoned and added a migration guide mentioning you alerting me to this fact. ;) I will probably see you again in a PR somewhere soon!

**Comment by szepeviktor** [comment]
@PrinsFrank I see Composer as an experimental software used by millions...

**Comment by szepeviktor** [comment]
> I will probably see you again in a PR somewhere soon!

# 👋🏻

**Pull request closed without merging**
